// Generated by CoffeeScript 1.7.1
(function($, host) {
  var hostMap, item, mp4, mp4s, selector, style, _i, _len, _ref;
  hostMap = {
    "m.tv.sohu.com": "#main_player video"
  };
  selector = hostMap[host];
  if (!selector) {
    return false;
  }
  mp4s = JSON.parse((_ref = $('script').html().replace(/\s|\n/g, "").match(/mp4:(.*?])/)) != null ? _ref[1] : void 0);
  if (mp4s) {
    for (_i = 0, _len = mp4s.length; _i < _len; _i++) {
      item = mp4s[_i];
      mp4 = item;
    }
  }
  style = ["display: block", "position: fixed", "width: 40px", "right: 1em", "bottom: 2em", "height: 40px", "text-indent: -999em", "padding: 1em 0", "font-size: 1.6em", "background: url(http://tv.sohu.com/upload/sohuapp/download/skin/download_icon@2x.png)", "background-size: 70% 70%", "background-color: #ccc", "border-radius: 4px", "background-repeat: no-repeat", "background-position: center"].join(";");
  return $('body').append($("<a href=\"" + mp4 + "\" style=\"" + style + "\"></a>"));
})(Zepto, location.host);
